model:
  module_name: models.unet_mobilenetv2
  class_name: UnetMobileNetV2Model
  batch_norm: True
  learning_rate: 1.0e-3
  alpha: 0.5

trainer:
  module_name: trainers.reduce_lr_on_plateau
  class_name: ReduceLROnPlateauTrainer
  tensorboard_enabled: True
  log_directory: experiments/small_unet/logs
  model_checkpoint: True
  epochs: 30
  reduce_lr_on_plateau:
    monitor: val_loss
    factor: 0.1
    patience: 5
    min_delta: 1.0e-2

data_preprocessing:
  module_name: data_preprocessing.augmentation
  class_name: AugmentationPreprocessing
  image_size: [192, 192]
  background_class_weight: 0.1

data:
  batch_size: 16
  prefetch: True
  prefetch_buffer_size: 10
  shuffle: True
  workers: 10

devices:
  memory_growth: False
