model:
  module_name: models.unet_iou
  class_name: UnetModel
  channels: [32, 64, 128]
  batch_norm: True
  learning_rate: 1.0e-3

trainer:
  module_name: trainers.reduce_lr_on_plateau
  class_name: ReduceLROnPlateauTrainer
  tensorboard_enabled: True
  log_directory: experiments/small_unet/logs
  model_checkpoint: True
  epochs: 20
  reduce_lr_on_plateau:
    monitor: val_loss
    factor: 0.1
    patience: 3
    min_delta: 1.0e-2

data_preprocessing:
  module_name: data_preprocessing.augmentation
  class_name: AugmentationPreprocessing
  image_size: [140, 284]
  background_class_weight: 0.1

data:
  batch_size: 4
  prefetch: True
  prefetch_buffer_size: 10
  shuffle: True
  shuffle_buffer_size: 100
  workers: 3

devices:
  memory_growth: True
